usr_name = input("What's your name?: ")
fav_food = input("What's your favourite food?: ")
fav_music = input("What's your favourite music?: ")
usr_home = input("Where do you live?: ")
print()
print("You are")
print(usr_name)
print("I bet you're probably hungry for")
print(fav_food)
print("and you are getting your groove on listening to")
print(fav_music)
print("on Spotify and heading straight to")
print(usr_home)